db.pet.insertMany([
    {
        _id: 1,
        Especie: 'cachorro',
        Raca: 'vira lata',
        Nome: 'fred',
        Sexo: 'M',
        DataNascimento: '10/05/2000',
        Vacinas: 'todas',
        Notas: 'nao entendi',
        client: [1],
    },
    {
        _id: 2,
        Especie: 'cachorro',
        Raca: 'vira lata',
        Nome: 'matraca',
        Sexo: 'M',
        DataNascimento: '10/05/2000',
        Vacinas: 'todas',
        Notas: 'nao entendi',
        client: [2],
    },
    {
        _id: 3,
        Especie: 'cachorro',
        Raca: 'husky',
        Nome: 'hulk',
        Sexo: 'M',
        DataNascimento: '10/05/2000',
        Vacinas: 'todas',
        Notas: 'nao entendi',
        client: [3],
    },
    {
        _id: 4,
        Especie: 'cachorro',
        Raca: 'pitbull',
        Nome: 'thor',
        Sexo: 'M',
        DataNascimento: '10/05/2000',
        Vacinas: 'todas',
        Notas: 'nao entendi',
        client: [4],
    },
    {
        _id: 5,
        Especie: 'cachorro',
        Raca: 'salsisha',
        Nome: 'luna',
        Sexo: 'F',
        DataNascimento: '10/05/2000',
        Vacinas: 'todas',
        Notas: 'nao entendi',
        client: [5],
    },
]);